######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 10 18:33:40 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += my_obj.hpp
SOURCES += dialog_demo.cpp
QT += script
