######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 9 17:49:54 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += dialog_demo.cpp
QT += script
